#!/bin/bash

echo "Is this your initial commit? (y/n)"

read init
if [[ $init = "y" ]]
then
	read -r -p "Commit message: " desc
	git init
	git add .
	git commit -m "$desc"
	echo Please insert your remote repository
	read link
	git remote add origin $link
	git push -u origin master
else
	read -r -p "Commit message: asdf" desc
	git add .
	git add -u
	git commit -m "$desc"
	git push origin master
fi
